apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: sq6tg7qyo-nodejs
  janus-idp.io/tekton: sq6tg7qyo-nodejs
  backstage.io/kubernetes-id: sq6tg7qyo-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sq6tg7qyo-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
