apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: sq6tg7qyo-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sq6tg7qyo-nodejs 
  name: sq6tg7qyo-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: sq6tg7qyo-nodejs 
